const ProductActionTypes = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_RECEIVED: 'PRODUCT_LIST_RECEIVED',
  PRODUCT_LIST_FAILURE: 'PRODUCT_LIST_FAILURE',
}

export default ProductActionTypes
