const ProductActionTypes = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_RECEIVED: 'PRODUCT_LIST_RECEIVED',
  PRODUCT_LIST_FAILURE: 'PRODUCT_LIST_FAILURE',

  PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_RECEIVED: 'PRODUCT_DETAILS_RECEIVED',
  PRODUCT_DETAILS_FAILURE: 'PRODUCT_DETAILS_FAILURE',
}

export default ProductActionTypes
